# frozen_string_literal: true

source "https://rubygems.org"

gem "hanami", git: "https://github.com/hanami/hanami.git", branch: "unstable"

group :plugins, :development do
  gem "hanami-reloader", path: "../../../"
end
